export default [
  {
    id: 1,
    propertyCategory: "Apartment",
    propertySubCategory: "Studio",
    propertyAddress: "Accra, New Town",
    propertyUnit: "",
    propertyLandmark: "",
    utilities: ["electricity", "water", "heating"],
    categories: ["vacation", "co-op-housing", "student-housing"],
    yearBuilt: "2003",
    petFriendly: "yes",
    furnished: "yes",
    leaseTerms: "one-year",
    otherDetails: "bathroom",
    bathroomType: "inside",
    parkingType: "garage",
    parkingSpots: 2,
    rent: 530,
    photos: ["/media/stock-900x600/2.jpg", "/media/stock-900x600/24.jpg"],
    // eslint-disable-next-line
    description: `The Lotus Elise first appeared in 1996 and revolutionised small sports car design with its lightweight extruded aluminium chassis and composite body. There have been many variations, but the basic principle remain the same.`,
    buildingFeatures: "24h-security",
    unitFeatures: "",
    nearbyFeat: "",
    leadEmail: "brytamegbor@gmail.com",
    leadPhone: "0558317703",
    status: "pending",
    plan: "free",
    timestamp: "2020-09-22 11:22:02"

  },
  // eslint-disable-next-line
  {
    id: 2,
    propertyCategory: "House",
    propertySubCategory: "house",
    propertyAddress: "Koforidua, Adweso",
    propertyUnit: "",
    propertyLandmark: "",
    utilities: ["electricity", "water"],
    categories: "student-housing",
    yearBuilt: "2010",
    petFriendly: "",
    furnished: "yes",
    leaseTerms: "one-year",
    otherDetails: "bathroom",
    bathroomType: "outside",
    parkingType: "",
    parkingSpots: 0,
    rent: 130,
    photos: ["/media/stock-900x600/24.jpg", "/media/stock-900x600/2.jpg"],
    // eslint-disable-next-line
    description: `The Lotus Elise first appeared in 1996 and revolutionised small sports car design with its lightweight extruded aluminium chassis and composite body. There have been many variations, but the basic principle remain the same.`,
    buildingFeatures: "24h-security",
    unitFeatures: "",
    nearbyFeat: "",
    leadEmail: "brytamegbor@gmail.com",
    leadPhone: "0558317703",
    status: "disapproved",
    plan: "free",
    timestamp: "2020-09-22 17:21:02"
  },
  {
    id: 3,
    propertyCategory: "House",
    propertySubCategory: "Cottage",
    propertyAddress: "Kumasi, Asafo",
    propertyUnit: "",
    propertyLandmark: "",
    utilities: ["electricity", "water"],
    categories: ["vacation", "co-op-housing", "student-housing"],
    yearBuilt: "2014",
    petFriendly: "",
    furnished: "yes",
    leaseTerms: "one-year",
    otherDetails: "bathroom",
    bathroomType: "outside",
    parkingType: "",
    parkingSpots: 0,
    rent: 200,
    photos: ["/media/stock-900x600/27.jpg", "/media/stock-900x600/1.jpg"],
    // eslint-disable-next-line
    description: `The Lotus Elise first appeared in 1996 and revolutionised small sports car design with its lightweight extruded aluminium chassis and composite body. There have been many variations, but the basic principle remain the same.`,
    buildingFeatures: "24h-security",
    unitFeatures: "",
    nearbyFeat: "",
    leadEmail: "brytamegbor@gmail.com",
    leadPhone: "0558317703",
    status: "active",
    plan: "free",
    timestamp: "2020-09-22 14:22:02",
  },
  {
    id: 4,
    propertyCategory: "Room",
    propertySubCategory: "Single Room",
    propertyAddress: "Cape Coast",
    propertyUnit: "",
    propertyLandmark: "",
    utilities: ["electricity", "water"],
    categories: ["vacation", "co-op-housing", "student-housing"],
    yearBuilt: "2013",
    petFriendly: "",
    furnished: "yes",
    leaseTerms: "one-year",
    otherDetails: "bathroom",
    bathroomType: "inside",
    parkingType: "",
    parkingSpots: 0,
    rent: 450,
    photos: ["/media/stock-900x600/1.jpg", "/media/stock-900x600/27.jpg"],
    // eslint-disable-next-line
    description: `The Lotus Elise first appeared in 1996 and revolutionised small sports car design with its lightweight extruded aluminium chassis and composite body. There have been many variations, but the basic principle remain the same.`,
    buildingFeatures: "24h-security",
    unitFeatures: "",
    nearbyFeat: "",
    leadEmail: "brytamegbor@gmail.com",
    leadPhone: "0558317703",
    status: "disabled",
    plan: "free",
    timestamp: "2020-09-22 13:22:02"
  },

];
